name: Build QuietDaemon

on:
  workflow_dispatch:

jobs:
  build-macos-intel:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (Intel)
        run: python3 compile.py

      - name: Upload QuietDaemon.app (Intel)
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_macOS_intel
          path: dist/QuietDaemon.app

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (ARM)
        run: python3 compile.py

      - name: Upload QuietDaemon.app (ARM)
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_macOS_arm
          path: dist/QuietDaemon.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows
        run: python compile.py

      - name: Upload QuietDaemon (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_Windows
          path: dist/QuietDaemon
