name: Build QuietDaemon

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version is this release?'
        required: true

jobs:
  build-macos-intel:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (Intel)
        run: python compile.py

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Upload QuietDaemon.app (Intel)
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_macOS_intel
          path: dist/QuietDaemon.app

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MacOS (ARM)
        run: python compile.py

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Upload QuietDaemon.app (ARM)
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_macOS_arm
          path: dist/QuietDaemon.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows
        run: python compile.py

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Upload QuietDaemon.exe
        uses: actions/upload-artifact@v4
        with:
          name: QuietDaemon_Windows
          path: dist/QuietDaemon.exe
